In [1]:
import tensorflow as tf
import tensorflow_datasets as tfds
from layers import MyDense

c:\Users\otkul\ETH\vår\project\.env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
(temp, ds_test), ds_info = tfds.load(
    'mnist',
    split=['train', 'test'],
    shuffle_files=True,
    as_supervised=True,
    with_info=True
)
ds_train = temp



In [3]:
def normalize_img(image, label):
    return tf.cast(image, tf.float32)/255., label
ds_train = ds_train.map(normalize_img)
ds_train = ds_train.cache()
ds_train = ds_train.shuffle(ds_info.splits['train'].num_examples)
ds_train = ds_train.batch(128)
ds_train = ds_train.prefetch(tf.data.AUTOTUNE)

In [4]:
ds_test = ds_test.map(normalize_img)
ds_test = ds_test.batch(128)
ds_test = ds_test.cache()
ds_test = ds_test.prefetch(tf.data.AUTOTUNE)

In [5]:

# model = tf.keras.models.Sequential([
#     tf.keras.layers.Flatten(input_shape=(28, 28)),
#     tf.keras.layers.Dense(128),
#     tf.keras.layers.LeakyReLU(),
#     tf.keras.layers.Dense(10)
# ])

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    MyDense(128),
    tf.keras.layers.LeakyReLU(),
    MyDense(10)
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(0.001),
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=[tf.keras.metrics.SparseCategoricalAccuracy()],
)

model.fit(
    ds_train,
    epochs=6,
    validation_data=ds_test
)

ValueError: Exception encountered when calling layer "my_dense" (type MyDense).

in user code:

    File "c:\Users\otkul\ETH\vår\project\layers.py", line 20, in call  *
        return tf.keras.activations.relu(tf.matmul(self.w, inputs) + self.b)

    ValueError: Dimensions must be equal, but are 784 and 128 for '{{node my_dense/add}} = AddV2[T=DT_FLOAT](my_dense/MatMul, my_dense/add/ReadVariableOp)' with input shapes: [784,784], [128].


Call arguments received by layer "my_dense" (type MyDense):
  • inputs=tf.Tensor(shape=(None, 784), dtype=float32)

In [ ]:
import numpy as np

a = np.arange(6).reshape((2, 3))
b = (2+np.arange(6)).reshape((3, -1))
print(a)
print(b)

c = np.einsum("bid, bjd -> bijd", a, b)

ii, jj, kk = c.shape
for i in range(ii):
    for j in range(jj):
        for k in range(kk):
            print(f"{c[i, j, k]} = {a[i,j]} x {b[j,k]}")

[[0 1 2]
 [3 4 5]]
[[2 3]
 [4 5]
 [6 7]]


ValueError: einstein sum subscripts string contains too many subscripts for operand 0