In [1]:
import tensorflow as tf
import keras.backend as K

In [ ]:
# # B, N, N, L = inputs.shape
#         N = inputs.shape[1]

#         totsum = tf.einsum("...ijl->...l", inputs)/self.average_particles**2    # B x L
#         rowsum = tf.einsum("...iil->...il", inputs)/self.average_particles          # B x N x L

#         ops = [None] * 6

#         ONES = tf.ones((N, N), dtype=tf.float32)
#         IDENTITY = tf.eye(N, dtype=tf.float32)

#         # Identity
#         ops[0] = inputs

#         # Totsum over entire output
#         ops[1] = tf.einsum("...l, ij->...ijl", totsum, ONES)

#         # Rowsum broadcasted over rows
#         ops[2] = tf.einsum("...nl, nj->...njl", rowsum, ONES)

#         # Rowsum broadcasted over columns
#         ops[3] = tf.einsum("...nl, nj->...jnl", rowsum, ONES)

#         # Rowsum broadcast over diagonals
#         ops[4] = tf.einsum("...nl, nj->...njl", rowsum, IDENTITY)

#         #   totsum broadcast over diagonals
#         ops[5] = tf.einsum("...l, ij->...ijl", totsum, IDENTITY)
#         ops = tf.stack(ops, axis=-1) # B x N x N x L x 6


#         diag_bias = tf.einsum("f, ij->ijf", self.diag_bias, IDENTITY)
#         return self.activation(
#             (tf.einsum("...ijlk, lkf->...ijf", ops, self.w)
#             + self.bias
#             + diag_bias))

In [41]:
inputs = tf.reshape(tf.range(3*3*2, dtype=tf.float32), (3, 3, 2))
totsum = tf.einsum("...ijl->...l", inputs)
# rowsum = tf.einsum("...iil->...il", inputs)
rowsum = tf.reduce_sum(inputs, axis=-2)

trace = tf.einsum("iil->l", inputs)
print(trace)
print(inputs[:, :, -2])

N = inputs.shape[0]

tf.Tensor([24. 27.], shape=(2,), dtype=float32)
tf.Tensor(
[[ 0.  2.  4.]
 [ 6.  8. 10.]
 [12. 14. 16.]], shape=(3, 3), dtype=float32)


In [38]:
ONES = tf.ones((N, N), dtype=tf.float32)
IDENTITY = tf.eye(N, dtype=tf.float32)

# Totsum over entire output
ops = tf.einsum("...l, ij->...ijl", totsum, ONES)

# Rowsum broadcasted over rows
ops = tf.einsum("...nl, nj->...njl", rowsum, ONES)

# Rowsum broadcasted over columns
ops = tf.einsum("...nl, nj->...jnl", rowsum, ONES)

# Rowsum broadcast over diagonals
ops = tf.einsum("...nl, nj->...njl", rowsum, IDENTITY)

ops = tf.einsum("...l, ij->...ijl", totsum, IDENTITY)


totsum  = tf.einsum("bijl->bl", inputs)/self.average_particles**2         # B x L
trace   = tf.einsum("biil->bl", inputs)

print(ss[:, :, -2])

tf.Tensor(
[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]], shape=(3, 3), dtype=float32)
