In [3]:
import h5py
from pathlib import Path

In [4]:
root = Path('raw')

for dir in root.iterdir():

    for file in dir.iterdir():
        h5_file = h5py.File(file)

        feats = h5_file['jetConstituentList'][:, :, :4]
        labels = h5_file['jets'][:, -6:-1]


        with h5py.File(Path(dir.name) / file.name, 'w') as new_file:
            new_file.create_dataset('feats', data=feats)
            new_file.create_dataset('label', data=labels)



In [5]:
import numpy as np

arr = np.zeros((10, 4))


for i in range(len(arr)):
    arr[i][np.random.randint(0, 4)] = 1

print(arr)

[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]]


In [6]:
arr = np.argmax(arr, axis=1)
print(arr)

[2 0 3 2 0 2 0 0 1 1]
