In [20]:
import h5py
from pathlib import Path
import os

In [21]:
root = Path('raw')

for file in (root / 'test').iterdir():
    print(file.name)
    h5_file = h5py.File(file)
    print(h5_file.keys())
    print(h5_file['particleFeatureNames'][:])
    break


jetImage_8_150p_0_10000.h5
<KeysViewHDF5 ['jetConstituentList', 'jetFeatureNames', 'jetImage', 'jetImageECAL', 'jetImageHCAL', 'jets', 'particleFeatureNames']>
[b'j1_px' b'j1_py' b'j1_pz' b'j1_e' b'j1_erel' b'j1_pt' b'j1_ptrel'
 b'j1_eta' b'j1_etarel' b'j1_etarot' b'j1_phi' b'j1_phirel' b'j1_phirot'
 b'j1_deltaR' b'j1_costheta' b'j1_costhetarel' b'j1_pdgid']


In [22]:
# ptetaphi_rel

for dir in root.iterdir():

    os.mkdir(dir.name)

    for file in dir.iterdir():
        h5_file = h5py.File(file)

        feats = h5_file['jetConstituentList'][:, :, [5, 8, 11]]
        labels = h5_file['jets'][:, -6:-1]


        with h5py.File(Path(dir.name) / file.name, 'w') as new_file:
            new_file.create_dataset('feats', data=feats)
            new_file.create_dataset('label', data=labels)



In [23]:
# Fourvec

for dir in root.iterdir():

    os.mkdir(dir.name)
    for file in dir.iterdir():
        h5_file = h5py.File(file)

        feats = h5_file['jetConstituentList'][:, :, :4]
        labels = h5_file['jets'][:, -6:-1]


        with h5py.File(Path(dir.name) / file.name, 'w') as new_file:
            new_file.create_dataset('feats', data=feats)
            new_file.create_dataset('label', data=labels)



FileExistsError: [WinError 183] Kan ikke opprette en fil når filen allerede finnes: 'test'

In [37]:
import tensorflow as tf

eta = 1e1
p_T = tf.exp(-eta)
phi = 0.0

print(p_T, eta, phi)
A = tf.stack([
    [p_T, eta, phi],
    [p_T, -eta, phi]
], axis=0)

print(A)

tf.Tensor(4.539993e-05, shape=(), dtype=float32) 10.0 0.0
tf.Tensor(
[[ 4.539993e-05  1.000000e+01  0.000000e+00]
 [ 4.539993e-05 -1.000000e+01  0.000000e+00]], shape=(2, 3), dtype=float32)


In [38]:
import tensorflow as tf

y_true = tf.Variable([[2.0],[0.0],[0.0],[3.0],[4.0]])
y_pred = tf.Variable([[2.0],[-1.0],[1.0],[3.0],[4.0]])

def my_loss_function(y_true, y_pred):

    print('y_true:')
    print(y_true)
    print('y_pred:')
    print(y_pred)

    y_zeros = tf.zeros_like(y_pred)
    print('y_zeros:')
    print(y_zeros)

    y_mask = tf.math.greater(y_pred, y_zeros)
    print('y_mask:')
    print(y_mask)

    res = tf.boolean_mask(y_pred, y_mask)
    print('res:')
    print(res)

    logres = tf.math.log(res)
    print('logres:')
    print(logres)

    finres = tf.math.reduce_sum(logres)
    print('finres:')
    print(finres)

    return finres

myres = my_loss_function(y_true, y_pred)
print(myres)

y_true:
<tf.Variable 'Variable:0' shape=(5, 1) dtype=float32, numpy=
array([[2.],
       [0.],
       [0.],
       [3.],
       [4.]], dtype=float32)>
y_pred:
<tf.Variable 'Variable:0' shape=(5, 1) dtype=float32, numpy=
array([[ 2.],
       [-1.],
       [ 1.],
       [ 3.],
       [ 4.]], dtype=float32)>
y_zeros:
tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]], shape=(5, 1), dtype=float32)
y_mask:
tf.Tensor(
[[ True]
 [False]
 [ True]
 [ True]
 [ True]], shape=(5, 1), dtype=bool)
res:
tf.Tensor([2. 1. 3. 4.], shape=(4,), dtype=float32)
logres:
tf.Tensor([0.6931472 0.        1.0986123 1.3862944], shape=(4,), dtype=float32)
finres:
tf.Tensor(3.1780539, shape=(), dtype=float32)
tf.Tensor(3.1780539, shape=(), dtype=float32)


In [47]:
import tensorflow as tf
import numpy as np

A = np.random.randint(low=0, high=2, size=(100, 50, 4))
A = tf.cast(A, dtype=tf.float32)

particle_sum = tf.reduce_sum(tf.abs(A), axis=-1)
nonzero_indeces = tf.cast(particle_sum > 1.0e-6, tf.int32)
print(nonzero_indeces)

# print(A)
print(A[0])


tf.Tensor(
[[1 0 1 ... 1 1 1]
 [1 1 0 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]], shape=(100, 50), dtype=int32)
tf.Tensor(
[[0. 0. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 1. 1.]
 [1. 1. 1. 0.]
 [1. 1. 0. 0.]
 [0. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 1. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 1. 1.]
 [1. 0. 1. 1.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [1. 1. 0. 1.]
 [1. 1. 0. 1.]
 [1. 1. 0. 1.]
 [0. 0. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 0. 1.]
 [1. 1. 0. 1.]
 [0. 1. 1. 1.]
 [1. 1. 1. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 1.]
 [0. 1. 1. 1.]
 [1. 0. 1. 0.]
 [1. 1. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 1. 1.]
 [1. 1. 0. 1.]
 [0. 0. 0. 0.]
 [0. 1. 1. 1.]
 [0. 1. 1. 0.]
 [1. 1. 1. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 1. 1. 0.]
 [0. 0. 1. 1.]
 [1. 0. 1. 1.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 1. 0. 0.]
 [1. 1. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 1. 0.]], shape=(50, 4), dtype=float32)
